[project]
name = "octollama"
version = "0.1.0"
description = "Run many Ollama instances"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "prometheus-client>=0.22.0",
]
